name: PR Workflow

on:
  pull_request:
    branches:
      - master  # Adjust as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: |
          python -m pip install pipx
          python -m pipx install poetry
          python -m pipx ensurepath
          poetry install

      - name: Install Graphviz
        run: sudo apt-get install graphviz

      - name: Run Tests
        run: |
          poetry shell
          poetry run pytest

      - name: Generate UML Diagrams
        run: pyreverse -o png ./apis/

      - name: Build Documentation
        run: |
          sphinx-build -E -b html docs/source docs/build  

      - name: Move Diagrams
        run: mv ./*.png /docs/build/_static/

      - name: Commit Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Auto-generate UML diagrams and documentation"
          git push

      # Optionally, tag the commit
      - name: Tag Commit
        if: success() && github.event_name == 'pull_request'
        run: |
          TAG=$(poetry version | cut -d' ' -f2)
          COMMIT_ABBR=$(git log --abbrev-commit -n 1 --format="%h")
          echo "$TAG-$COMMIT_ABBR"
          git tag "$TAG-$COMMIT_ABBR"
          git push origin "$TAG-$COMMIT_ABBR"